server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
    # active: dev
  data:
    redis:
      host: 10.21.160.28
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.160.28:8848