spring:
  application:
    name: admin
  datasource:

    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 10.21.160.28
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.160.28:8848
server:
  port: 8002
short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20