server:
  port: 8001

spring:
  application:
    name: project
  datasource:
    driverClassName: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
    username: master
    password: fhe@404.
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  data:
    redis:
      host: 10.21.160.28
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.160.28:8848
short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml